// ============================================================================
// AI Service Types - TypeScript Interfaces for AI Project Generation
// ============================================================================

import type { RecurrencePattern, TaskType } from '@/types';

// ============================================================================
// Input Types - What the user provides
// ============================================================================

/**
 * Input for AI project generation
 */
export interface AIProjectInput {
    /** Free-form user description of the project they want to create */
    description: string;
    /** ID of the user creating the project */
    creatorId: number;
}

// ============================================================================
// Output Types - What the AI returns via n8n
// ============================================================================

/**
 * A task generated by AI as part of a project
 */
export interface AIGeneratedTask {
    /** Task title (max 100 chars) */
    title: string;
    /** Brief task description (max 200 chars) */
    description: string;
    /** Days from now for due date (0 = today, 7 = next week, etc.) */
    daysFromNow: number;
    /** Type of task */
    type: TaskType;
    /** Recurrence pattern for habit tasks */
    recurrencePattern?: RecurrencePattern;
    /** Custom interval in days (only if pattern is 'custom') */
    recurrenceInterval?: number;
}

/**
 * A complete project generated by AI including tasks
 */
export interface AIGeneratedProject {
    /** Project name (max 50 chars) */
    name: string;
    /** Brief project description (max 200 chars) */
    description: string;
    /** Icon name from PROJECT_ICONS */
    icon: string;
    /** HSL color string */
    color: string;
    /** Whether the project is public */
    isPublic: boolean;
    /** Array of generated tasks */
    tasks: AIGeneratedTask[];
}

// ============================================================================
// State Types - For React hooks
// ============================================================================

/**
 * State of AI project generation process
 */
export type AIProjectState = 'idle' | 'loading' | 'success' | 'error';

/**
 * Result of the generate project action
 */
export interface GenerateProjectResult {
    success: boolean;
    project?: AIGeneratedProject;
    error?: string;
}

// ============================================================================
// API Response Types - Raw response from n8n
// ============================================================================

/**
 * Raw response format from n8n Gemini node
 */
export interface N8nGeminiResponse {
    content?: {
        parts?: Array<{ text?: string }>;
    };
}
